//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.21 at 12:51:38 PM BRT 
//


package city.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="juridicalAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="directorName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="directorPosition" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="baseAction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="unp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="receivingBank" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bik" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="landlineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyInfo", propOrder = {
    "companyName",
    "juridicalAddress",
    "directorName",
    "directorPosition",
    "baseAction",
    "unp",
    "receivingBank",
    "bik",
    "accountNumber",
    "landlineNumber"
})
public class CompanyInfo {

    @XmlElement(required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String juridicalAddress;
    @XmlElement(required = true)
    protected String directorName;
    @XmlElement(required = true)
    protected String directorPosition;
    @XmlElement(required = true)
    protected String baseAction;
    @XmlElement(required = true)
    protected String unp;
    @XmlElement(required = true)
    protected String receivingBank;
    @XmlElement(required = true)
    protected String bik;
    protected int accountNumber;
    @XmlElement(required = true)
    protected String landlineNumber;

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the juridicalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJuridicalAddress() {
        return juridicalAddress;
    }

    /**
     * Sets the value of the juridicalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJuridicalAddress(String value) {
        this.juridicalAddress = value;
    }

    /**
     * Gets the value of the directorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorName() {
        return directorName;
    }

    /**
     * Sets the value of the directorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorName(String value) {
        this.directorName = value;
    }

    /**
     * Gets the value of the directorPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorPosition() {
        return directorPosition;
    }

    /**
     * Sets the value of the directorPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorPosition(String value) {
        this.directorPosition = value;
    }

    /**
     * Gets the value of the baseAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseAction() {
        return baseAction;
    }

    /**
     * Sets the value of the baseAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseAction(String value) {
        this.baseAction = value;
    }

    /**
     * Gets the value of the unp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnp() {
        return unp;
    }

    /**
     * Sets the value of the unp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnp(String value) {
        this.unp = value;
    }

    /**
     * Gets the value of the receivingBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivingBank() {
        return receivingBank;
    }

    /**
     * Sets the value of the receivingBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivingBank(String value) {
        this.receivingBank = value;
    }

    /**
     * Gets the value of the bik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBik() {
        return bik;
    }

    /**
     * Sets the value of the bik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBik(String value) {
        this.bik = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     */
    public int getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     */
    public void setAccountNumber(int value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the landlineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLandlineNumber() {
        return landlineNumber;
    }

    /**
     * Sets the value of the landlineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLandlineNumber(String value) {
        this.landlineNumber = value;
    }

}
