//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.21 at 12:51:38 PM BRT 
//


package city.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the city.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: city.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AcceptRequestRequest }
     * 
     */
    public AcceptRequestRequest createAcceptRequestRequest() {
        return new AcceptRequestRequest();
    }

    /**
     * Create an instance of {@link RequestAcceptParam }
     * 
     */
    public RequestAcceptParam createRequestAcceptParam() {
        return new RequestAcceptParam();
    }

    /**
     * Create an instance of {@link AcceptRequestResponse }
     * 
     */
    public AcceptRequestResponse createAcceptRequestResponse() {
        return new AcceptRequestResponse();
    }

    /**
     * Create an instance of {@link GetCityRequest }
     * 
     */
    public GetCityRequest createGetCityRequest() {
        return new GetCityRequest();
    }

    /**
     * Create an instance of {@link GetCityResponse }
     * 
     */
    public GetCityResponse createGetCityResponse() {
        return new GetCityResponse();
    }

    /**
     * Create an instance of {@link GetTourRequest }
     * 
     */
    public GetTourRequest createGetTourRequest() {
        return new GetTourRequest();
    }

    /**
     * Create an instance of {@link GetTourResponse }
     * 
     */
    public GetTourResponse createGetTourResponse() {
        return new GetTourResponse();
    }

    /**
     * Create an instance of {@link Tour }
     * 
     */
    public Tour createTour() {
        return new Tour();
    }

    /**
     * Create an instance of {@link FindTourRequest }
     * 
     */
    public FindTourRequest createFindTourRequest() {
        return new FindTourRequest();
    }

    /**
     * Create an instance of {@link FindTourResponse }
     * 
     */
    public FindTourResponse createFindTourResponse() {
        return new FindTourResponse();
    }

    /**
     * Create an instance of {@link AddRequestRequest }
     * 
     */
    public AddRequestRequest createAddRequestRequest() {
        return new AddRequestRequest();
    }

    /**
     * Create an instance of {@link AddRequestResponse }
     * 
     */
    public AddRequestResponse createAddRequestResponse() {
        return new AddRequestResponse();
    }

    /**
     * Create an instance of {@link FindRequestRequest }
     * 
     */
    public FindRequestRequest createFindRequestRequest() {
        return new FindRequestRequest();
    }

    /**
     * Create an instance of {@link FindRequestResponse }
     * 
     */
    public FindRequestResponse createFindRequestResponse() {
        return new FindRequestResponse();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link FindUserResponse }
     * 
     */
    public FindUserResponse createFindUserResponse() {
        return new FindUserResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link FindUserRequest }
     * 
     */
    public FindUserRequest createFindUserRequest() {
        return new FindUserRequest();
    }

    /**
     * Create an instance of {@link AuthRequest }
     * 
     */
    public AuthRequest createAuthRequest() {
        return new AuthRequest();
    }

    /**
     * Create an instance of {@link AuthResponse }
     * 
     */
    public AuthResponse createAuthResponse() {
        return new AuthResponse();
    }

    /**
     * Create an instance of {@link AddUserRequest }
     * 
     */
    public AddUserRequest createAddUserRequest() {
        return new AddUserRequest();
    }

    /**
     * Create an instance of {@link PersonInfo }
     * 
     */
    public PersonInfo createPersonInfo() {
        return new PersonInfo();
    }

    /**
     * Create an instance of {@link CompanyInfo }
     * 
     */
    public CompanyInfo createCompanyInfo() {
        return new CompanyInfo();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link AddUserResponse }
     * 
     */
    public AddUserResponse createAddUserResponse() {
        return new AddUserResponse();
    }

    /**
     * Create an instance of {@link Seats }
     * 
     */
    public Seats createSeats() {
        return new Seats();
    }

    /**
     * Create an instance of {@link SeatSet }
     * 
     */
    public SeatSet createSeatSet() {
        return new SeatSet();
    }

}
