//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.21 at 12:51:38 PM BRT 
//


package city.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tour complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tour"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tourId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="departureDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="departureHour" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="departureMin" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="seatsCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="seatSet" type="{http://www.abelski.by/ws}seatSet"/&gt;
 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tour", propOrder = {
    "tourId",
    "departureDate",
    "departureHour",
    "departureMin",
    "seatsCount",
    "seatSet",
    "from",
    "to"
})
public class Tour {

    @XmlElement(required = true)
    protected String tourId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar departureDate;
    protected int departureHour;
    protected int departureMin;
    protected int seatsCount;
    @XmlElement(required = true)
    protected SeatSet seatSet;
    @XmlElement(required = true)
    protected String from;
    @XmlElement(required = true)
    protected String to;

    /**
     * Gets the value of the tourId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTourId() {
        return tourId;
    }

    /**
     * Sets the value of the tourId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTourId(String value) {
        this.tourId = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDate(XMLGregorianCalendar value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the departureHour property.
     * 
     */
    public int getDepartureHour() {
        return departureHour;
    }

    /**
     * Sets the value of the departureHour property.
     * 
     */
    public void setDepartureHour(int value) {
        this.departureHour = value;
    }

    /**
     * Gets the value of the departureMin property.
     * 
     */
    public int getDepartureMin() {
        return departureMin;
    }

    /**
     * Sets the value of the departureMin property.
     * 
     */
    public void setDepartureMin(int value) {
        this.departureMin = value;
    }

    /**
     * Gets the value of the seatsCount property.
     * 
     */
    public int getSeatsCount() {
        return seatsCount;
    }

    /**
     * Sets the value of the seatsCount property.
     * 
     */
    public void setSeatsCount(int value) {
        this.seatsCount = value;
    }

    /**
     * Gets the value of the seatSet property.
     * 
     * @return
     *     possible object is
     *     {@link SeatSet }
     *     
     */
    public SeatSet getSeatSet() {
        return seatSet;
    }

    /**
     * Sets the value of the seatSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeatSet }
     *     
     */
    public void setSeatSet(SeatSet value) {
        this.seatSet = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

}
